spring:
  application.name: demo-password-encoder

  datasource:
    driver-class-name: org.h2.Driver
    url: ${db.url:jdbc:h2:mem:testdb}
    username: ${db.username:sa}
    password: ${db.password:}
    hikari:
      connectionTimeout: 30_000
      idleTimeout: 600_000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 30_000
      leak-detection-threshold: 2000

  jpa:
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
